apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kb-{{ include "clustername" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "pika-cluster.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources:
      - events
    verbs:
      - create
  - apiGroups: ["apps.kubeblocks.io"]
    resources:
      - clusters
    verbs:
      - get
      - list
      - watch
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
