apiVersion: apps.kubeblocks.io/v1alpha1
kind: ComponentDefinition
metadata:
  name: pika
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pika.labels" . | nindent 4 }}
spec:
  provider: pika
  description: Pika component definition
  serviceKind: pika
  serviceVersion: {{ .Chart.AppVersion }}
  services:
    - name: pika
      spec:
        ports:
          - name: pika
            port: 9221
            targetPort: pika
  updateStrategy: Serial
  configs:
    - name: config
      templateRef: pika-master-slave-conf-template
      namespace: {{ .Release.Namespace }}
      volumeName: config
  volumes:
    - name: data
  roles:
    - name: master
      serviceable: true
      writable: true
    - name: slave
      serviceable: false
      writable: false
  lifecycleActions:
    roleProbe:
      builtinHandler: custom 
      customHandler:
        image: {{ include "redis.image" .}}
        exec:
          command:
            - /bin/bash
            - -c
            - |
              replication_info=$(redis-cli -h 127.0.0.1 -p 9221 info replication)
              role=$(echo "${replication_info}" | awk -F':' '/^role:/ {print $2}' | tr -d '[:space:]')
              if [ "$role"x = "master"x ]; then
                echo -n "master"
              else
                echo -n "slave"
              fi  
      periodSeconds: 1
      timeoutSeconds: 1
  runtime:
    initContainers:
      - name: init-config
        image: busybox:1.28
        imagePullPolicy: IfNotPresent
        command:
          - /bin/sh
          - -ec
          - |
            if [ ! -f "/data/pika.conf" ];then cp /etc/pika/pika.conf /data/pika.conf; fi
        volumeMounts:
          - name: config
            mountPath: /etc/pika
          - name: data
            mountPath: /data  
    containers:
      - name: pika
        image: {{ include "pika.image" . }}
        imagePullPolicy: {{ include "pika.imagePullPolicy" . }}
        ports:
          - name: pika
            containerPort: 9221
        volumeMounts:
          - name: config
            mountPath: /etc/pika
          - name: data
            mountPath: /data
        env:
          - name: CURRENT_POD_HOST_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.hostIP
        command:
          - "/pika/bin/pika"
        args:
          - "-c"
          - "/data/pika.conf"
      - name: redis-cli-runner
        image: {{ include "redis.image" . }}
        imagePullPolicy: {{ include "pika.imagePullPolicy" . }}
        command:
          - /bin/bash
          - -c
          - |
            while true; do
              hostname=$KB_POD_NAME
              if [[ "$hostname" =~ -([0-9]+)$ ]]; then
                ordinal=${BASH_REMATCH[1]}
                if [[ $ordinal -ge 1 && $ordinal -le 9 ]]; then
                  replication_info=$(redis-cli -h 127.0.0.1 -p 9221 info replication)
                  role=$(echo "${replication_info}" | awk -F':' '/^role:/ {print $2}' | tr -d '[:space:]')
                  if [ "$role"x = "master"x ]; then
                    redis-cli -h 127.0.0.1 -p 9221 slaveof pika-master-slave-cluster-pika-0.pika-master-slave-cluster-pika-headless 9221
                  fi
                fi
              fi
              sleep 10
            done
          
